parameters:
    profileImage_directory: '%kernel.project_dir%/public/uploads/profileImages'
    productImage_directory: '%kernel.project_dir%/public/uploads/productImages'

services:
    _defaults:
        autowire: true
        autoconfigure: true.

    App\:
        resource: '../src/'

    App\Service\TelegramService:
        arguments:
            $botToken: '%env(TELEGRAM_BOT_TOKEN)%'
            $chatId: '%env(TELEGRAM_CHAT_ID)%'
